#+TITLE: Trabalho prático de Teste de Software

* Integrantes

 - Bárbara Gomes Ribeiro
 - Flávio Lúcio Corrêa Júnior
 - Vinícios Julião Ramos

* Descrição do trabalho

O trabalho consiste na escrita de um programa e um conjunto de testes. Os testes devem seguir as boas práticas descritas nas aulas da disciplina. O trabalho será dividido em duas etapas que consistem em:

** Etapa 1

- Projetar e implementar um sistema e software
- Implementar 50 testes de unidade (API públicas, comportamento, focados, não-complexos e etc)
- Configurar ferramenta de CI/CD Github Actions e rodar a bateria de testes em cada commit

** Etapa 2

- Implementar 5 testes de integração ou e2e
- Rodar  cobertura  de  testes  no  workflow  do  GitHub  Actions
- Publicar  os  relatórios  de  cobertura  no  Codecov  através  do  GitHub  Actionw


* Projeto do sistema

*** Qual sistema implementar?

A principal premissa a seguir é que seja algo de rápida implementação e alta testabilidade. Seguindo essa linha, decidiu-se implementar uma biblioteca de algoritmos e estruturas de dados. O sistema consiste nos seguintes módulos:

- `queue`
- `stack`
- `linked list`
- `undirected graph`
- `directed graph`
- `tree`
- `quick_sort`
- `merge_sort`
- `bubble sort`
- `binary_search`
- `BFS`
- `DFS`

Pensando em uma aplicação didática e na necessidade de implementar testes de 
integração/e2e, decidiu-se implementar um repl, o qual funciona com os seguintes comandos:

#+begin_src
create {queue | stack | list | undirected_graph | directed_graph} <STRUCTURE_NAME>
delete <STRUCTURE_NAME>
add <STRUCTURE_NAME> <ELEMENT> [position]
remove <STRUCTURE_NAME>
#+end_src

Para queue, stack e linked list apenas:

#+begin_src
sort {quick_sort | merge_sort | bubble_sort} <STRUCTURE_NAME>
search binary <STRUCTURE_NAME> <ELEMENT>
#+end_src

Para grafos apenas:

#+begin_src
search {bfs | dfs} <STRUCTURE_NAME> <START_NODE_ID>
add <STRUCTURE_NAME> edge <NODE_ID_1> <NODE_ID_2>
add <STRUCTURE_NAME> node <NODE_ID>
remove <STRUCTURE_NAME> <NODE_ID>
#+end_src


*** Com qual tech stack?

As tecnologias escolhidas foram:

- Linguagem de programação: Python
- Gerenciador de dependências: Poetry
- Biblioteca de testes: Pytest
- Linter: Flake8
- Formatter: Black, Isort

* Como executar

*** Como executar o repl:

#+begin_src
python main.py
#+end_src

*** Para desenvolvedores:

Instale a ferramenta de gerenciamento de dependências `poetry`:

#+begin_src
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
source $HOME/.poetry/env
#+end_src

Ative o ambiente virtual:

#+begin_src
poetry shell
#+end_src

Instale as dependências:

#+begin_src
poetry install
#+end_src

Rode a bateria de testes:

#+begin_src
poetry run pytest --cov .
#+end_src

Rode o programa principal:

#+begin_src
poetry run python main.py
#+end_src

Você pode querer formatar o código ou rodar o linter antes de abrir um PR, isso pode ser feito direto no seu editor de texto ou executando a CLI:

- Linter:

#+begin_src
flake8 . --count
#+end_src

- Formatter:

#+begin_src
black .
#+end_src
